[lab01]

[[lab01.dates]]
suffix = "due"
date = "2025-08-28"
percentage = 1.0

[project01]

[[project01.dates]]
suffix = "due"
date = "2025-09-03"
percentage = 1.0

[[project01.dates]]
suffix = "1week-late"
date = "2025-09-12"
percentage = 0.75

[[project01.dates]]
suffix = "super-late"
date = "2025-12-09"
percentage = 0.50

[lab02]

[[lab02.dates]]
suffix = "due"
date = "2025-09-04"
percentage = 1.0

[lab03]

[[lab03.dates]]
suffix = "due"
date = "2025-09-10"
percentage = 1.0

[lab04]

[[lab04.dates]]
suffix = "due"
date = "2025-09-20"
percentage = 1.0

[project02]

[[project02.dates]]
suffix = "due"
date = "2025-09-16"
percentage = 1.0

[[project02.dates]]
suffix = "1week-late"
date = "2025-09-23"
percentage = 0.75

[[project02.dates]]
suffix = "super-late"
date = "2025-12-09"
percentage = 0.50

[project03]

[[project03.dates]]
suffix = "due"
date = "2025-09-23"
percentage = 1.0

[[project03.dates]]
suffix = "1week-late"
date = "2025-09-30"
percentage = 0.75

[[project03.dates]]
suffix = "super-late"
date = "2025-12-09"
percentage = 0.50

[lab05]

[[lab05.dates]]
suffix = "due"
date = "2025-09-30"
percentage = 1.0

[lab06]

[[lab06.dates]]
suffix = "due"
date = "2025-10-01"
percentage = 1.0

[project04]

[[project04.dates]]
suffix = "due"
date = "2025-10-08"
percentage = 1.0

[[project04.dates]]
suffix = "1week-late"
date = "2025-10-15"
percentage = 0.75

[[project04.dates]]
suffix = "super-late"
date = "2025-12-09"
percentage = 0.50
